import AppKit
import AVFoundation
import CoreAudio

/// The selected 180 ms wood tap is bundled locally, at the same level as the audition.
final class DictationStartSound {
    private let player: AVAudioPlayer?
    init() {
        let url = Bundle.main.url(forResource: "dictation-start", withExtension: "wav", subdirectory: "Sounds")
            ?? Bundle.module.url(forResource: "dictation-start", withExtension: "wav", subdirectory: "Sounds")
        player = url.flatMap { try? AVAudioPlayer(contentsOf: $0) }
        player?.volume = 1
        player?.prepareToPlay()
    }
    /// Returns the time to leave output audible before applying recording mute.
    func play() -> TimeInterval {
        guard let player else { return 0 }
        player.currentTime = 0
        return player.play() ? player.duration + 0.04 : 0
    }
    func stop() { player?.stop() }
}

/// Mutes the default output while recording, and unmutes only what it muted itself.
final class SystemAudioMute {
    private var mutedDevice: AudioDeviceID?
    private static var muteAddress = AudioObjectPropertyAddress(mSelector: kAudioDevicePropertyMute, mScope: kAudioDevicePropertyScopeOutput, mElement: kAudioObjectPropertyElementMain)
    func mute() {
        guard mutedDevice == nil, let device = Self.defaultOutput(), Self.isMuted(device) == false, Self.setMuted(device, true) else { return }
        mutedDevice = device
    }
    func restore() {
        guard let device = mutedDevice else { return }
        mutedDevice = nil; _ = Self.setMuted(device, false)
    }
    private static func defaultOutput() -> AudioDeviceID? {
        var address = AudioObjectPropertyAddress(mSelector: kAudioHardwarePropertyDefaultOutputDevice, mScope: kAudioObjectPropertyScopeGlobal, mElement: kAudioObjectPropertyElementMain)
        var device = AudioDeviceID(0); var size = UInt32(MemoryLayout<AudioDeviceID>.size)
        return AudioObjectGetPropertyData(AudioObjectID(kAudioObjectSystemObject), &address, 0, nil, &size, &device) == noErr && device != 0 ? device : nil
    }
    private static func isMuted(_ device: AudioDeviceID) -> Bool? {
        guard AudioObjectHasProperty(device, &muteAddress) else { return nil }
        var value = UInt32(0); var size = UInt32(MemoryLayout<UInt32>.size)
        return AudioObjectGetPropertyData(device, &muteAddress, 0, nil, &size, &value) == noErr ? value != 0 : nil
    }
    private static func setMuted(_ device: AudioDeviceID, _ muted: Bool) -> Bool {
        var value = UInt32(muted ? 1 : 0)
        return AudioObjectSetPropertyData(device, &muteAddress, 0, nil, UInt32(MemoryLayout<UInt32>.size), &value) == noErr
    }
}

/// Fallback when the host has no LinkInput connection: a transient clipboard item and ⌘V, never Return.
/// The previous clipboard comes back afterwards unless the user copied something else meanwhile.
enum ClipboardPaster {
    static func paste(_ text: String) {
        let board = NSPasteboard.general
        let saved: [[(NSPasteboard.PasteboardType, Data)]] = (board.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
        }
        board.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // nspasteboard.org markers: clipboard managers skip transient, generated content.
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString(Bundle.main.bundleIdentifier ?? "LinkInput", forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
        board.writeObjects([item])
        let ours = board.changeCount
        let source = CGEventSource(stateID: .privateState)
        for down in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: down)
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) {
            guard board.changeCount == ours else { return }
            board.clearContents()
            let items = saved.map { entries -> NSPasteboardItem in
                let restored = NSPasteboardItem(); entries.forEach { restored.setData($0.1, forType: $0.0) }; return restored
            }
            if !items.isEmpty { board.writeObjects(items) }
        }
    }
}
